spring:
  datasource:
    url: jdbc:mysql://你的远程mysqlIP:3306/test_report?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: 你的mysql账号
    password: 你的mysql密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapper/*.xml  # 简化路径
    type-aliases-package: io.github.asthenia0412.pipelinestatemachine.model
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      # 添加这些配置
      call-setters-on-nulls: true
      jdbc-type-for-null: OTHER
logging:
  level:
    org.mybatis: INFO
    org.springframework.jdbc: INFO
    io.github.asthenia0412.pipelinestatemachine.mapper: TRACE  # 你的 Mapper 包路径
  task:
    scheduling:
      pool:
        size: 10
server:
  port: 8080